import { test, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { env, retryCount, dryRun } from './ExerciseConfigReader';

/**
 * VALIDATION for module 5 — do not edit this file.
 * Run with: ./exercises/run.sh 5
 */

afterEach(() => {
  delete process.env['app.env'];
  delete process.env['retry.count'];
  delete process.env['dry.run'];
});

test('reads values from the properties file', () => {
  assert.equal(env(), 'staging');
  assert.equal(retryCount(), 3);
  assert.equal(dryRun(), false);
});

test('an environment variable overrides the file', () => {
  process.env['app.env'] = 'production';

  assert.equal(env(), 'production', 'an env var of the same name must win over the properties file');
});

test('file value applies again once the override is cleared', () => {
  process.env['retry.count'] = '9';
  assert.equal(retryCount(), 9);

  delete process.env['retry.count'];
  assert.equal(retryCount(), 3, 'falls back to exercise.properties once the override is cleared');
});

test('boolean override works too', () => {
  process.env['dry.run'] = 'true';

  assert.equal(dryRun(), true, 'an env var override must work for boolean getters too');
});
