import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readDiscount } from './DiscountDataReader';
import { applyDiscount } from './PriceCalculator';

/**
 * VALIDATION for module 4 — do not edit this file.
 * Run with: ./exercises/run.sh 4
 */

test('reads known discount codes', () => {
  const save10 = readDiscount('SAVE10');
  assert.equal(save10.percentOff, 10);
  assert.equal(save10.description, '10% off');

  const welcome = readDiscount('WELCOME');
  assert.equal(welcome.percentOff, 5);
});

test('unknown code throws an Error naming the code', () => {
  assert.throws(
    () => readDiscount('NOT_A_REAL_CODE'),
    (err: unknown) => err instanceof Error && err.message.includes('NOT_A_REAL_CODE'),
    'mirrors CsvDataReader.getRowByTestCaseId\'s behaviour for a missing key'
  );
});

test('applies a discount across several data rows', () => {
  const cases: Array<[priceSum: number, percentOff: number, expected: number]> = [
    [100.0, 10, 90.0],
    [100.0, 25, 75.0],
    [50.0, 0, 50.0],
    [80.0, 50, 40.0],
  ];

  for (const [priceSum, percentOff, expected] of cases) {
    const actual = applyDiscount([priceSum], percentOff);
    assert.ok(
      Math.abs(actual - expected) < 0.01,
      `prices summing to ${priceSum} with ${percentOff}% off -> expected ~${expected}, got ${actual}`
    );
  }
});

test('sums multiple prices before discounting', () => {
  const actual = applyDiscount([10.0, 20.0, 30.0], 10.0); // (10 + 20 + 30) * 0.9 = 54
  assert.ok(Math.abs(actual - 54.0) < 0.01);
});
