import { test, before, after, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { chromium, Browser, Page } from '@playwright/test';
import { BurgerMenuPage } from './BurgerMenuPage';
import { LoginPage } from '../../../pages/LoginPage';
import { InventoryPage } from '../../../pages/InventoryPage';

/**
 * VALIDATION for module 3 — do not edit this file.
 * Run with: ./exercises/run.sh 3
 *
 * Includes both a code-quality check (locators must be private, via a source-text
 * scan — enforcing POM rule 1 automatically, the TypeScript equivalent of the
 * reflection-based check a Java version of this exercise would use, since
 * TypeScript's `private` is a compile-time-only construct) and functional checks
 * against a real browser.
 */

let browser: Browser;
let page: Page;

before(async () => {
  browser = await chromium.launch({ headless: process.env.HEADLESS !== 'false' });
});

after(async () => {
  await browser.close();
});

beforeEach(async () => {
  page = await browser.newPage();
  const loginPage = new LoginPage(page);
  await loginPage.open();
  await loginPage.login('standard_user', 'secret_sauce');
});

afterEach(async () => {
  await page.close();
});

test('all Locator fields are declared private (POM rule 1)', () => {
  const sourcePath = path.resolve(__dirname, 'BurgerMenuPage.ts');
  const source = fs.readFileSync(sourcePath, 'utf-8');

  // Matches class-field declarations typed `: Locator;` at the start of a line
  // (ignoring constructor assignments like `this.foo = ...`, which never match
  // this shape), capturing any leading access modifier.
  const fieldDeclarationPattern = /^\s*(public\s+|protected\s+|private\s+)?(readonly\s+)?(\w+)\s*:\s*Locator\s*;/gm;
  const fieldDeclarations = [...source.matchAll(fieldDeclarationPattern)];

  assert.ok(fieldDeclarations.length > 0, 'expected at least one Locator field declared on BurgerMenuPage');

  for (const [, modifier, , fieldName] of fieldDeclarations) {
    assert.equal(
      modifier?.trim(),
      'private',
      `POM rule 1 (notes/03-page-object-model.md): Locator field '${fieldName}' must be declared 'private'`
    );
  }
});

test('openMenu() makes the menu open', async () => {
  const menu = new BurgerMenuPage(page);

  assert.equal(await menu.isMenuOpen(), false, 'menu should start closed');
  await menu.openMenu();
  assert.equal(await menu.isMenuOpen(), true, 'menu should be open after openMenu()');
});

test('logout() returns to the login page', async () => {
  const menu = new BurgerMenuPage(page);

  await menu.openMenu();
  const loginPage = await menu.logout();

  assert.ok(loginPage instanceof LoginPage, 'logout() must return a LoginPage');
  assert.ok(!page.url().includes('inventory.html'), 'logging out should navigate away from inventory.html');
});

test('resetAppState() clears the cart', async () => {
  const inventoryPage = new InventoryPage(page);
  await inventoryPage.addProductToCart('Sauce Labs Backpack');
  assert.equal(await inventoryPage.getCartCount(), 1);

  const menu = new BurgerMenuPage(page);
  await menu.openMenu();
  await menu.resetAppState();

  assert.equal(await inventoryPage.getCartCount(), 0, 'cart count after Reset App State');
});
