import { test, before, after, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { chromium, Browser, Page } from '@playwright/test';
import { fillLoginForm, clickLoginButton, readErrorMessage, isElementVisible } from './PlaywrightBasicsExercise';

/**
 * VALIDATION for module 1 — do not edit this file.
 * Run with: ./exercises/run.sh 1
 *
 * Each test drives a REAL browser against saucedemo.com using ONLY the functions
 * you implement in PlaywrightBasicsExercise.ts. If a function still throws
 * "TODO: implement ...", its test(s) fail and the error names the TODO you still
 * need to finish — that's your automated checklist.
 */

const BASE_URL = 'https://www.saucedemo.com';

let browser: Browser;
let page: Page;

before(async () => {
  browser = await chromium.launch({ headless: process.env.HEADLESS !== 'false' });
});

after(async () => {
  await browser.close();
});

beforeEach(async () => {
  page = await browser.newPage();
  await page.goto(BASE_URL);
});

afterEach(async () => {
  await page.close();
});

test('fillLoginForm fills both fields', async () => {
  await fillLoginForm(page, 'standard_user', 'secret_sauce');

  assert.equal(
    await page.locator('#user-name').inputValue(),
    'standard_user',
    'username field should contain what fillLoginForm typed'
  );
  assert.equal(
    await page.locator('#password').inputValue(),
    'secret_sauce',
    'password field should contain what fillLoginForm typed'
  );
});

test('clickLoginButton navigates to inventory after a valid login', async () => {
  await fillLoginForm(page, 'standard_user', 'secret_sauce');
  await clickLoginButton(page);

  assert.ok(
    page.url().includes('inventory.html'),
    'clicking login with valid credentials should navigate to inventory.html'
  );
});

test('readErrorMessage reads the trimmed error banner text', async () => {
  await fillLoginForm(page, 'locked_out_user', 'secret_sauce');
  await clickLoginButton(page);

  const message = await readErrorMessage(page);
  assert.ok(
    message.includes('Sorry, this user has been locked out'),
    `error banner text after logging in as locked_out_user was: "${message}"`
  );
});

test('isElementVisible reflects real visibility', async () => {
  assert.equal(
    await isElementVisible(page, '#login-button'),
    true,
    'login button should be visible before any login attempt'
  );
  assert.equal(
    await isElementVisible(page, "[data-test='error']"),
    false,
    'error banner should not be visible before any failed login'
  );

  await fillLoginForm(page, 'locked_out_user', 'secret_sauce');
  await clickLoginButton(page);

  assert.equal(
    await isElementVisible(page, "[data-test='error']"),
    true,
    'error banner should be visible after a failed login'
  );
});
