import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  CartSteps,
  GIVEN_EMPTY_CART_PATTERN,
  WHEN_ADD_ITEM_PATTERN,
  WHEN_REMOVE_ITEM_PATTERN,
  THEN_CART_COUNT_PATTERN,
} from './CartSteps';

/**
 * VALIDATION for module 2 — do not edit this file.
 * Run with: ./exercises/run.sh 2
 *
 * Checks two things, matching the two parts of the task:
 *  (a) each pattern constant holds the exact Cucumber Expression a real
 *      Given/When/Then call would use (a string-equality check — the same string
 *      real Cucumber would try to match a .feature line against).
 *  (b) calling the methods in Gherkin scenario order produces the right cart
 *      state (behavioural check).
 */

test('Cucumber Expression patterns match exactly', () => {
  assert.equal(GIVEN_EMPTY_CART_PATTERN, 'an empty shopping cart');
  assert.equal(WHEN_ADD_ITEM_PATTERN, 'I add {string} to the cart');
  assert.equal(WHEN_REMOVE_ITEM_PATTERN, 'I remove {string} from the cart');
  assert.equal(THEN_CART_COUNT_PATTERN, 'the cart should contain {int} item(s)');
});

test('behaves like the example scenario', () => {
  const steps = new CartSteps();

  steps.givenAnEmptyShoppingCart();
  steps.whenIAddItemToTheCart('Sauce Labs Backpack');
  steps.whenIAddItemToTheCart('Sauce Labs Bike Light');
  steps.whenIRemoveItemFromTheCart('Sauce Labs Backpack');

  assert.equal(steps.getCart().size(), 1, 'cart size after add, add, remove');
  assert.equal(steps.getCart().contains('Sauce Labs Bike Light'), true);
  assert.equal(steps.getCart().contains('Sauce Labs Backpack'), false);

  assert.doesNotThrow(() => steps.thenCartShouldContainItems(1));
});

test('the Then step actually asserts, not just reads', () => {
  const steps = new CartSteps();
  steps.whenIAddItemToTheCart('Sauce Labs Backpack');

  assert.throws(
    () => steps.thenCartShouldContainItems(5),
    'thenCartShouldContainItems must throw when the count is wrong, not just read it'
  );
});
